/* Source of ISO 4217: https://en.wikipedia.org/wiki/ISO_4217
The database should only contain the current active currency codes, used by at least one country,
not including fund codes.
The format property defines how the currency's values are displayed.

Example - For Denmark's currency "Krone" also referred to as "Danish Crowns";
          code: 'DKK'
          id: '208'
          format: '%value% kr.'

          Would be display like so: '206,65 kr.'

Whenever a price is displayed, we will look for a format, and if none is found (null), the price will be displayed raw,
otherwise we'll parse the price to the format, and display it like so,allowing all currencies to be properly displayed.
*/
export const currencies: { code: string, id: string, format: string | null }[] = [
    {code: 'N/A', id: '000', format: null},
    {code: 'AED', id: '784', format: null},
    {code: 'AFN', id: '971', format: null},
    {code: 'ALL', id: '008', format: null},
    {code: 'AMD', id: '051', format: null},
    {code: 'AOA', id: '973', format: null},
    {code: 'ARS', id: '032', format: null},
    {code: 'AUD', id: '036', format: null},
    {code: 'AWG', id: '533', format: null},
    {code: 'AZN', id: '944', format: null},
    {code: 'BAM', id: '977', format: null},
    {code: 'BBD', id: '052', format: null},
    {code: 'BDT', id: '050', format: null},
    {code: 'BHD', id: '048', format: null},
    {code: 'BIF', id: '108', format: null},
    {code: 'BMD', id: '060', format: null},
    {code: 'BND', id: '096', format: null},
    {code: 'BOB', id: '068', format: null},
    {code: 'BRL', id: '986', format: null},
    {code: 'BSD', id: '044', format: null},
    {code: 'BTN', id: '064', format: null},
    {code: 'BWP', id: '072', format: null},
    {code: 'BYN', id: '933', format: null},
    {code: 'BZD', id: '084', format: null},
    {code: 'CAD', id: '124', format: null},
    {code: 'CDF', id: '976', format: null},
    {code: 'CHF', id: '756', format: null},
    {code: 'CLP', id: '152', format: null},
    {code: 'CNY', id: '156', format: null},
    {code: 'COP', id: '170', format: null},
    {code: 'CRC', id: '188', format: null},
    {code: 'CUP', id: '192', format: null},
    {code: 'CVE', id: '132', format: null},
    {code: 'CZK', id: '203', format: null},
    {code: 'DJF', id: '262', format: null},
    {code: 'DKK', id: '208', format: `%value% kr.`},
    {code: 'DOP', id: '214', format: null},
    {code: 'DZD', id: '012', format: null},
    {code: 'EGP', id: '818', format: null},
    {code: 'ERN', id: '232', format: null},
    {code: 'ETB', id: '230', format: null},
    {code: 'EUR', id: '978', format: `%value% €`},
    {code: 'FJD', id: '242', format: null},
    {code: 'FKP', id: '238', format: null},
    {code: 'GBP', id: '826', format: `£ %value%`},
    {code: 'GEL', id: '981', format: null},
    {code: 'GHS', id: '936', format: null},
    {code: 'GIP', id: '292', format: null},
    {code: 'GMD', id: '270', format: null},
    {code: 'GNF', id: '324', format: null},
    {code: 'GTQ', id: '320', format: null},
    {code: 'GYD', id: '328', format: null},
    {code: 'HKD', id: '344', format: null},
    {code: 'HNL', id: '340', format: null},
    {code: 'HTG', id: '332', format: null},
    {code: 'HUF', id: '348', format: null},
    {code: 'IDR', id: '360', format: null},
    {code: 'ILS', id: '376', format: null},
    {code: 'INR', id: '356', format: null},
    {code: 'IQD', id: '368', format: null},
    {code: 'IRR', id: '364', format: null},
    {code: 'ISK', id: '352', format: null},
    {code: 'JMD', id: '388', format: null},
    {code: 'JOD', id: '400', format: null},
    {code: 'JPY', id: '392', format: null},
    {code: 'KES', id: '404', format: null},
    {code: 'KGS', id: '417', format: null},
    {code: 'KHR', id: '116', format: null},
    {code: 'KMF', id: '174', format: null},
    {code: 'KPW', id: '408', format: null},
    {code: 'KRW', id: '410', format: null},
    {code: 'KWD', id: '414', format: null},
    {code: 'KYD', id: '136', format: null},
    {code: 'KZT', id: '398', format: null},
    {code: 'LAK', id: '418', format: null},
    {code: 'LBP', id: '422', format: null},
    {code: 'LKR', id: '144', format: null},
    {code: 'LRD', id: '430', format: null},
    {code: 'LSL', id: '426', format: null},
    {code: 'LYD', id: '434', format: null},
    {code: 'MAD', id: '504', format: null},
    {code: 'MDL', id: '498', format: null},
    {code: 'MGA', id: '969', format: null},
    {code: 'MKD', id: '807', format: null},
    {code: 'MMK', id: '104', format: null},
    {code: 'MNT', id: '496', format: null},
    {code: 'MOP', id: '446', format: null},
    {code: 'MRU', id: '929', format: null},
    {code: 'MUR', id: '480', format: null},
    {code: 'MVR', id: '462', format: null},
    {code: 'MWK', id: '454', format: null},
    {code: 'MXN', id: '484', format: null},
    {code: 'MYR', id: '458', format: null},
    {code: 'MZN', id: '943', format: null},
    {code: 'NAD', id: '516', format: null},
    {code: 'NGN', id: '566', format: null},
    {code: 'NIO', id: '558', format: null},
    {code: 'NOK', id: '578', format: `%value% kr.`},
    {code: 'NPR', id: '524', format: null},
    {code: 'NZD', id: '554', format: null},
    {code: 'OMR', id: '512', format: null},
    {code: 'PAB', id: '590', format: null},
    {code: 'PEN', id: '604', format: null},
    {code: 'PGK', id: '598', format: null},
    {code: 'PHP', id: '608', format: null},
    {code: 'PKR', id: '586', format: null},
    {code: 'PLN', id: '985', format: null},
    {code: 'PYG', id: '600', format: null},
    {code: 'QAR', id: '634', format: null},
    {code: 'RON', id: '946', format: null},
    {code: 'RSD', id: '941', format: null},
    {code: 'RUB', id: '643', format: null},
    {code: 'RWF', id: '646', format: null},
    {code: 'SAR', id: '682', format: null},
    {code: 'SBD', id: '090', format: null},
    {code: 'SCR', id: '690', format: null},
    {code: 'SDG', id: '938', format: null},
    {code: 'SEK', id: '752', format: `%value% kr.`},
    {code: 'SGD', id: '702', format: null},
    {code: 'SHP', id: '654', format: null},
    {code: 'SLE', id: '925', format: null},
    {code: 'SOS', id: '706', format: null},
    {code: 'SRD', id: '968', format: null},
    {code: 'SSP', id: '728', format: null},
    {code: 'STN', id: '930', format: null},
    {code: 'SVC', id: '222', format: null},
    {code: 'SYP', id: '760', format: null},
    {code: 'SZL', id: '748', format: null},
    {code: 'THB', id: '764', format: null},
    {code: 'TJS', id: '972', format: null},
    {code: 'TMT', id: '934', format: null},
    {code: 'TND', id: '788', format: null},
    {code: 'TOP', id: '776', format: null},
    {code: 'TRY', id: '949', format: null},
    {code: 'TTD', id: '780', format: null},
    {code: 'TWD', id: '901', format: null},
    {code: 'TZS', id: '834', format: null},
    {code: 'UAH', id: '980', format: null},
    {code: 'UGX', id: '800', format: null},
    {code: 'USD', id: '840', format: `$%value%`},
    {code: 'UYU', id: '858', format: null},
    {code: 'UZS', id: '860', format: null},
    {code: 'VED', id: '926', format: null},
    {code: 'VES', id: '928', format: null},
    {code: 'VND', id: '704', format: null},
    {code: 'VUV', id: '548', format: null},
    {code: 'WST', id: '882', format: null},
    {code: 'XAF', id: '950', format: null},
    {code: 'XCD', id: '951', format: null},
    {code: 'XCG', id: '532', format: null},
    {code: 'XOF', id: '952', format: null},
    {code: 'XPF', id: '953', format: null},
    {code: 'YER', id: '886', format: null},
    {code: 'ZAR', id: '710', format: null},
    {code: 'ZMW', id: '967', format: null},
    {code: 'ZWG', id: '924', format: null}];

export default currencies;