export interface Currency {
    code: string,
    format: string | null
}

/* Source of ISO 4217: https://en.wikipedia.org/wiki/ISO_4217
The database should only contain the current active currency codes, used by at least one country,
not including fund codes.
The format property defines how the currency's values are displayed.

Example - For Denmark's currency "Krone" also referred to as "Danish Crowns";
          code: 'DKK'
          id: '208'
          format: '%value% kr.'

          Would be display like so: '206,65 kr.'

Whenever a price is displayed, we will look for a format, and if none is found (null), the price will be displayed raw,
otherwise we'll parse the price to the format, and display it like so,allowing all currencies to be properly displayed.
*/
export const currencies: Map<string,string> = new Map<string,string>([
    ['N/A', '%value%'],
    ['AED', '%value%'],
    ['AFN', '%value%'],
    ['ALL', '%value%'],
    ['AMD', '%value%'],
    ['AOA', '%value%'],
    ['ARS', '%value%'],
    ['AUD', '%value%'],
    ['AWG', '%value%'],
    ['AZN', '%value%'],
    ['BAM', '%value%'],
    ['BBD', '%value%'],
    ['BDT', '%value%'],
    ['BHD', '%value%'],
    ['BIF', '%value%'],
    ['BMD', '%value%'],
    ['BND', '%value%'],
    ['BOB', '%value%'],
    ['BRL', '%value%'],
    ['BSD', '%value%'],
    ['BTN', '%value%'],
    ['BWP', '%value%'],
    ['BYN', '%value%'],
    ['BZD', '%value%'],
    ['CAD', '%value%'],
    ['CDF', '%value%'],
    ['CHF', '%value%'],
    ['CLP', '%value%'],
    ['CNY', '%value%'],
    ['COP', '%value%'],
    ['CRC', '%value%'],
    ['CUP', '%value%'],
    ['CVE', '%value%'],
    ['CZK', '%value%'],
    ['DJF', '%value%'],
    ['DKK', `%value% kr.`],
    ['DOP', '%value%'],
    ['DZD', '%value%'],
    ['EGP', '%value%'],
    ['ERN', '%value%'],
    ['ETB', '%value%'],
    ['EUR', `%value% €`],
    ['FJD', '%value%'],
    ['FKP', '%value%'],
    ['GBP', `£ %value%`],
    ['GEL', '%value%'],
    ['GHS', '%value%'],
    ['GIP', '%value%'],
    ['GMD', '%value%'],
    ['GNF', '%value%'],
    ['GTQ', '%value%'],
    ['GYD', '%value%'],
    ['HKD', '%value%'],
    ['HNL', '%value%'],
    ['HTG', '%value%'],
    ['HUF', '%value%'],
    ['IDR', '%value%'],
    ['ILS', '%value%'],
    ['INR', '%value%'],
    ['IQD', '%value%'],
    ['IRR', '%value%'],
    ['ISK', '%value%'],
    ['JMD', '%value%'],
    ['JOD', '%value%'],
    ['JPY', '%value%'],
    ['KES', '%value%'],
    ['KGS', '%value%'],
    ['KHR', '%value%'],
    ['KMF', '%value%'],
    ['KPW', '%value%'],
    ['KRW', '%value%'],
    ['KWD', '%value%'],
    ['KYD', '%value%'],
    ['KZT', '%value%'],
    ['LAK', '%value%'],
    ['LBP', '%value%'],
    ['LKR', '%value%'],
    ['LRD', '%value%'],
    ['LSL', '%value%'],
    ['LYD', '%value%'],
    ['MAD', '%value%'],
    ['MDL', '%value%'],
    ['MGA', '%value%'],
    ['MKD', '%value%'],
    ['MMK', '%value%'],
    ['MNT', '%value%'],
    ['MOP', '%value%'],
    ['MRU', '%value%'],
    ['MUR', '%value%'],
    ['MVR', '%value%'],
    ['MWK', '%value%'],
    ['MXN', '%value%'],
    ['MYR', '%value%'],
    ['MZN', '%value%'],
    ['NAD', '%value%'],
    ['NGN', '%value%'],
    ['NIO', '%value%'],
    ['NOK', `%value% kr.`],
    ['NPR', '%value%'],
    ['NZD', '%value%'],
    ['OMR', '%value%'],
    ['PAB', '%value%'],
    ['PEN', '%value%'],
    ['PGK', '%value%'],
    ['PHP', '%value%'],
    ['PKR', '%value%'],
    ['PLN', '%value%'],
    ['PYG', '%value%'],
    ['QAR', '%value%'],
    ['RON', '%value%'],
    ['RSD', '%value%'],
    ['RUB', '%value%'],
    ['RWF', '%value%'],
    ['SAR', '%value%'],
    ['SBD', '%value%'],
    ['SCR', '%value%'],
    ['SDG', '%value%'],
    ['SEK', `%value% kr.`],
    ['SGD', '%value%'],
    ['SHP', '%value%'],
    ['SLE', '%value%'],
    ['SOS', '%value%'],
    ['SRD', '%value%'],
    ['SSP', '%value%'],
    ['STN', '%value%'],
    ['SVC', '%value%'],
    ['SYP', '%value%'],
    ['SZL', '%value%'],
    ['THB', '%value%'],
    ['TJS', '%value%'],
    ['TMT', '%value%'],
    ['TND', '%value%'],
    ['TOP', '%value%'],
    ['TRY', '%value%'],
    ['TTD', '%value%'],
    ['TWD', '%value%'],
    ['TZS', '%value%'],
    ['UAH', '%value%'],
    ['UGX', '%value%'],
    ['USD', `$%value%`],
    ['UYU', '%value%'],
    ['UZS', '%value%'],
    ['VED', '%value%'],
    ['VES', '%value%'],
    ['VND', '%value%'],
    ['VUV', '%value%'],
    ['WST', '%value%'],
    ['XAF', '%value%'],
    ['XCD', '%value%'],
    ['XCG', '%value%'],
    ['XOF', '%value%'],
    ['XPF', '%value%'],
    ['YER', '%value%'],
    ['ZAR', '%value%'],
    ['ZMW', '%value%'],
    ['ZWG', '%value%']]);

export default currencies;