import db from "$lib/server/db/index";
import { ALL_TABLES } from './schema'

export default async function execute(): Promise<void> {
    await createTables();
    await insertCurrencies();
}

async function createTables(): Promise<void> {
    for (const table in ALL_TABLES) {
        await db.begin(async sql => {
            await sql.unsafe(table);
        })
    }
}

/* Source of ISO 4217: https://en.wikipedia.org/wiki/ISO_4217
The database should only contain the current active currency codes, used by at least one country. */
async function insertCurrencies(): Promise<void> {
    const result = await db`
    SELECT *
    FROM currencies
    LIMIT 1`

    if(result.count != 0) return

    await db.begin(async sql => {
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('AED', '784')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('AFN', '971')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('ALL', '008')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('AMD', '051')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('AOA', '973')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('ARS', '032')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('AUD', '036')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('AWG', '533')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('AZN', '944')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('BAM', '977')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('BBD', '052')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('BDT', '050')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('BHD', '048')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('BIF', '108')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('BMD', '060')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('BND', '096')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('BOB', '068')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('BRL', '986')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('BSD', '044')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('BTN', '064')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('BWP', '072')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('BYN', '933')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('BZD', '084')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('CAD', '124')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('CDF', '976')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('CHF', '756')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('CLP', '152')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('CNY', '156')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('COP', '170')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('CRC', '188')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('CUP', '192')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('CVE', '132')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('CZK', '203')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('DJF', '262')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('DKK', '208')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('DOP', '214')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('DZD', '012')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('EGP', '818')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('ERN', '232')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('ETB', '230')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('EUR', '978')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('FJD', '242')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('FKP', '238')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('GBP', '826')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('GEL', '981')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('GHS', '936')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('GIP', '292')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('GMD', '270')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('GNF', '324')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('GTQ', '320')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('GYD', '328')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('HKD', '344')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('HNL', '340')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('HTG', '332')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('HUF', '348')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('IDR', '360')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('ILS', '376')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('INR', '356')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('IQD', '368')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('IRR', '364')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('ISK', '352')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('JMD', '388')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('JOD', '400')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('JPY', '392')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('KES', '404')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('KGS', '417')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('KHR', '116')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('KMF', '174')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('KPW', '408')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('KRW', '410')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('KWD', '414')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('KYD', '136')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('KZT', '398')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('LAK', '418')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('LBP', '422')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('LKR', '144')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('LRD', '430')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('LSL', '426')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('LYD', '434')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('MAD', '504')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('MDL', '498')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('MGA', '969')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('MKD', '807')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('MMK', '104')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('MNT', '496')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('MOP', '446')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('MRU', '929')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('MUR', '480')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('MVR', '462')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('MWK', '454')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('MXN', '484')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('MYR', '458')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('MZN', '943')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('NAD', '516')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('NGN', '566')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('NIO', '558')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('NOK', '578')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('NPR', '524')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('NZD', '554')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('OMR', '512')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('PAB', '590')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('PEN', '604')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('PGK', '598')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('PHP', '608')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('PKR', '586')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('PLN', '985')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('PYG', '600')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('QAR', '634')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('RON', '946')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('RSD', '941')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('RUB', '643')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('RWF', '646')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('SAR', '682')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('SBD', '090')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('SCR', '690')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('SDG', '938')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('SEK', '752')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('SGD', '702')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('SHP', '654')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('SLE', '925')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('SOS', '706')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('SRD', '968')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('SSP', '728')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('STN', '930')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('SVC', '222')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('SYP', '760')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('SZL', '748')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('THB', '764')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('TJS', '972')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('TMT', '934')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('TND', '788')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('TOP', '776')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('TRY', '949')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('TTD', '780')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('TWD', '901')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('TZS', '834')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('UAH', '980')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('UGX', '800')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('USD', '840')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('UYU', '858')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('UZS', '860')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('VED', '926')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('VES', '928')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('VND', '704')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('VUV', '548')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('WST', '882')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('XAF', '950')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('XCD', '951')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('XCG', '532')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('XOF', '952')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('XPF', '953')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('YER', '886')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('ZAR', '710')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('ZMW', '967')`)
        await sql.prepare(`INSERT INTO currencies(code, number) VALUES ('ZWG', '924')`)
    })
}